# Generated by Django 5.1.15 on 2026-09-29 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credit_balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_sessions', to='core.billingaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('reasoning_content', models.TextField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('kind', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('RESERVE', 'Reserve'), ('SETTLE', 'Settle'), ('REFUND', 'Refund')], max_length=10)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.billingaccount')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='core.creditledger')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ModelCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=160, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('tier', models.CharField(choices=[('Luna', 'Luna'), ('Terra', 'Terra'), ('Sol', 'Sol')], max_length=16)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], max_length=16)),
                ('input_rate_per_million', models.DecimalField(decimal_places=6, max_digits=16)),
                ('output_rate_per_million', models.DecimalField(decimal_places=6, max_digits=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('tier', 'display_name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('input_rate_per_million__gte', 0)), name='catalog_input_rate_nonnegative'), models.CheckConstraint(condition=models.Q(('output_rate_per_million__gte', 0)), name='catalog_output_rate_nonnegative')],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_sessions', to='core.modelcatalog'),
        ),
        migrations.CreateModel(
            name='UsageTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_tokens', models.IntegerField()),
                ('completion_tokens', models.IntegerField()),
                ('input_rate_per_million', models.DecimalField(decimal_places=6, max_digits=16)),
                ('output_rate_per_million', models.DecimalField(decimal_places=6, max_digits=16)),
                ('cost_usd', models.DecimalField(decimal_places=12, max_digits=22)),
                ('credit_debit', models.IntegerField()),
                ('is_estimated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usage_transaction', to='core.chatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_transactions', to='core.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_system_prompt', models.TextField(blank=True)),
                ('ai_memories_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('preference', 'Preference'), ('fact', 'Fact'), ('instruction', 'Instruction')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_items', to='core.userprofile')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='billingaccount',
            constraint=models.CheckConstraint(condition=models.Q(('credit_balance__gte', 0)), name='billing_account_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(('prompt_tokens__gte', 0)), name='chat_message_prompt_tokens_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(('completion_tokens__gte', 0)), name='chat_message_completion_tokens_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='creditledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('kind', 'DEPOSIT')), models.Q(('amount__lt', 0), ('kind', 'RESERVE')), ('kind', 'SETTLE'), models.Q(('amount__gt', 0), ('kind', 'REFUND')), _connector='OR'), name='credit_ledger_kind_amount_valid'),
        ),
        migrations.AddConstraint(
            model_name='creditledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ('DEPOSIT', 'RESERVE')), ('reservation__isnull', True)), models.Q(('kind__in', ('SETTLE', 'REFUND')), ('reservation__isnull', False)), _connector='OR'), name='credit_ledger_reservation_by_kind'),
        ),
        migrations.AddConstraint(
            model_name='creditledger',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ('SETTLE', 'REFUND'))), fields=('reservation',), name='credit_ledger_one_finalization_per_reservation'),
        ),
        migrations.AddConstraint(
            model_name='usagetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('prompt_tokens__gte', 0)), name='usage_prompt_tokens_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='usagetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('completion_tokens__gte', 0)), name='usage_completion_tokens_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='usagetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('input_rate_per_million__gte', 0)), name='usage_input_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='usagetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('output_rate_per_million__gte', 0)), name='usage_output_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='usagetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('cost_usd__gte', 0)), name='usage_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='usagetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('credit_debit__gte', 0)), name='usage_credit_debit_nonnegative'),
        ),
    ]
