# Generated by Django 5.1.15 on 2026-09-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usagetransaction_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='complete', max_length=16),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
